# Generated by Django 2.2.7 on 2019-11-28 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrusel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=30)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='Photos')),
            ],
        ),
        migrations.CreateModel(
            name='Galeriap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='')),
                ('descripcion', models.CharField(max_length=30)),
            ],
        ),
    ]
